resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/dmcarba/datarealm
    branch: master

jobs:
- name: build-and-verify
  plan:
  - get: source-code
    trigger: true
  - task: build-and-verify
    file: source-code/tasks/build.yml
    params:
      M2_SETTINGS_REPO_ID : {{m2-settings-repo-id}}
      M2_SETTINGS_REPO_USERNAME : {{m2-settings-repo-username}}
      M2_SETTINGS_REPO_PASSWORD : {{m2-settings-repo-password}}
      M2_SETTINGS_REPO_RELEASE_URI : {{m2-settings-repo-release-uri}}
      M2_SETTINGS_REPO_SNAPSHOT_URI : {{m2-settings-repo-snapshot-uri}}
    